Vagrant.configure("2") do |config|

  config.vm.define "master" do |master|
    master.vm.box = "centos/7"
    master.vm.hostname = "master.puppetlab.com"
    master.vm.provider "libvirt" do |lv|
      lv.memory = "2028"
    end
    master.vm.provision "ansible" do |ansible|
      ansible.playbook = "master.yml"
    end
  end

  config.vm.define "client" do |client|
    client.vm.box = "centos/7"
    client.vm.hostname = "client.puppetlab.com"
    client.vm.provider "libvirt" do |lv|
      lv.memory = "2028"
    end
    client.vm.provision "ansible" do |ansible|
      ansible.playbook = "client.yml"
    end
  end

end
  
