Vagrant.configure("2") do |config|
  
  config.vm.provider "libvirt" do |libvirt|
    libvirt.memory = 1024
  end

  config.vm.provider "virtualbox" do |vbox|
    vbox.memory = 1024
  end

  config.vm.box = "centos/7"
  config.vm.hostname = "ansibledev.cdp.it"

  config.vm.network "forwarded_port", guest: 80, host: 8080
 
  
  config.vm.provision "shell",
    inline: "yum install -y ansible git vim" 

end
