# Vagrantfile for Origin All-in-one Lab machine on CentOS7 

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "oslab.example.com"

  # If Vagrant is running on Windows and there is no rsync installed please uncomment this line.
  # config.vm.synced_folder ".", "/vagrant", disabled: true

  # Memory settings for virtualbox
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 8192
    vb.cpus = 2
  end

  # Memory settings for qemu/kvm
  config.vm.provider "libvirt" do |lv|
    lv.memory = 8192
    lv.cpus = 2
  end

  # Configure port forwaring on 8443/tcp (master REST api service) to grant access to cli and console from host.
  config.vm.network "forwarded_port", guest: 443, host: 8443, host_ip: "127.0.0.1"
  # Forward port exposed by Keystone API endpoint
  config.vm.network "forwarded_port", guest: 5000, host: 5000, host_ip: "127.0.0.1"

  # Shell provisioning begins here
  config.vm.provision "shell", run: "once", inline: <<-SHELL
    sudo yum install ansible -y
  SHELL

  # Run the ansible_local plugin
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "playbook.yml"
  end

end
