---
- name: Define the Keycloak process user
  user:
    name: "{{ keycloak_user }}"
    shell: "/sbin/nologin"
    system: true
    create_home: false

- name: Unarchive Keycloak release
  unarchive:
    src: "{{ keycloak_url }}"
    dest: "{{ install_path }}"
    remote_src: yes
    owner: "{{ keycloak_user }}"
    group: "{{ keycloak_group }}"
    creates: "{{ install_path }}/keycloak-{{ keycloak_version }}"


