Vagrant.configure("2") do |config|
  
  config.vm.provider "libvirt" do |libvirt|
    libvirt.memory = 2048
  end

  config.vm.box = "centos/7"
  config.vm.hostname = "gitlab.traininglab.com"

  config.vm.network "forwarded_port", guest: 80, host: 8080
  
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end
end
