Vagrant.configure("2") do |config|
  
  config.vm.box = "centos/7"
  config.vm.hostname = "myodoo.traininglab.com"

  config.vm.provider "libvirt" do |libvirt|
    libvirt.memory = 2048
  end

  # Network port forwarding
  config.vm.network "forwarded_port", guest: 8069, host: 8069
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 80, host: 10080
  
  # Ansible Provisioning
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end
end
