Vagrant.configure("2") do |config|
  
  config.vm.provider "libvirt" do |libvirt|
    libvirt.memory = 2048
  end

  config.vm.box = "centos/7"
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 9200, host: 9200
  
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end
end
