---
- hosts: all
  become: true
  become_user: root
  vars:
    data_dir: "/var/lib/etcd"
    extra_packages:
      - git
      - wget
      - tmux
      - tree
      - bind-utils
    origin_packages:
      - origin-clients
      - atomic-openshift-utils

  tasks:
    - name: Base package group is installed
      yum:
        name: "@base"
        state: latest

    - name: System is updated
      yum:
        name: "*"
        state: latest

    - name: Package Docker is installed
      yum:
        name: docker
        state: latest

    - name: Auxiliary packages are installed
      yum:
        name: "{{ item }}"
        state: latest
      with_items: "{{ extra_packages }}"

    - name: Docker group is present
      group:
        name: docker
        system: true
        state: present

    - name: Vagrant user is in the docker group
      user:
        name: vagrant
        groups: docker
        append: yes
        
    - name: Service firewalld is disabled
      service:
        name: firewalld
        state: stopped
        enabled: false

    - name: Origin repos are defined
      yum:
        name: centos-release-openshift-origin39
        state: latest

    - name: Origin CLI and Utils are installed
      yum:
        name: "{{ item }}"
        state: latest
      with_items: "{{ origin_packages }}"

    - name: Enable internal insecure registry
      lineinfile:
        path: /etc/sysconfig/docker
        regexp: "OPTIONS='--selinux-enabled --log-driver=journald --signature-verification=false'"
        line: "OPTIONS='--selinux-enabled --log-driver=journald --signature-verification=false --insecure-registry=172.30.0.0/16'"
        state: present

    - name: Docker service is started and enabled
      service:
        name: docker
        state: started
        enabled: true

    - name: Create the data directory
      file:
        name: "{{ data_dir }}"
        state: directory
        mode: 0755
    
    - name: Provision the management script
      copy:
        src: files/oc-cluster-up.sh
        dest: /home/vagrant
        owner: vagrant
        group: vagrant
        mode: 0755
