---
- name: "Configure Golab vagrant machine"
  hosts: all
  become: true
  become_user: root
  tasks:
    - include_role: 
        name: golang
      vars:
        go_dist: "https://dl.google.com/go/go1.11.1.linux-amd64.tar.gz"


